# Generated by Django 4.0.7 on 2024-01-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_device_model'),
        ('general', '0002_blogcategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogcategory',
            unique_together={('blog', 'category')},
        ),
    ]
