# Generated by Django 4.0.7 on 2024-01-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_blogcategory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
