# Generated by Django 4.0.7 on 2024-01-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_story_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='general.blog'),
        ),
    ]
