# Generated by Django 4.0.7 on 2024-01-24 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0005_alter_blogcategory_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('blog', 'user')},
        ),
    ]
