# Generated by Django 4.0.7 on 2024-01-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_comment_accepted_alter_comment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='location',
            field=models.IntegerField(choices=[(1, 'FIRST'), (2, 'SECOND'), (3, 'THRID'), (4, 'FOURTH')], unique=True),
        ),
    ]
