# Generated by Django 4.0.7 on 2024-01-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_alter_banner_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='picture',
            new_name='laptop_picture',
        ),
        migrations.AddField(
            model_name='slider',
            name='middle_picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='slider',
            name='mobile_picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
