# Generated by Django 4.0.7 on 2024-02-08 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_rename_picture_slider_laptop_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='phone_number')),
                ('description', models.TextField(max_length=500)),
                ('is_checked', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.contactformsubject')),
            ],
        ),
    ]
