# Generated by Django 4.0.7 on 2024-02-16 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_message_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.IntegerField(choices=[(1, 'ISSUE')])),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
