# Generated by Django 4.0.7 on 2024-02-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_rename_question_type_commonquestion_question_locaiton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonquestion',
            old_name='question_locaiton',
            new_name='question_location',
        ),
    ]
