# Generated by Django 4.0.7 on 2024-03-25 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_blog_created_at_blog_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
