# Generated by Django 4.0.7 on 2024-03-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0017_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
