# Generated by Django 4.0.7 on 2024-03-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0018_alter_contactform_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormSubject',
        ),
    ]
