# Generated by Django 4.0.7 on 2024-03-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='IssueCategory',
        ),
        migrations.DeleteModel(
            name='IssueReport',
        ),
    ]
