# Generated by Django 4.0.7 on 2024-03-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_alter_issuetag_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='explanation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
