# Generated by Django 4.0.7 on 2024-03-17 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_issuereport_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuelistreport',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_list_report', to='issue.issue'),
        ),
    ]
