# Generated by Django 4.0.7 on 2024-03-17 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_deliverydata_unique_together'),
        ('issue', '0006_alter_issuelistreport_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='delivery_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.deliverydata'),
        ),
    ]
