# Generated by Django 4.0.7 on 2024-03-18 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0007_alter_issuereport_delivery_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuelistreport',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.issue'),
        ),
        migrations.AlterField(
            model_name='issuelistreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_list_report', to='issue.issuereport'),
        ),
    ]
