# Generated by Django 4.0.7 on 2024-03-18 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0008_alter_issuelistreport_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuecategory',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='issue.issue'),
        ),
    ]
