# Generated by Django 4.0.7 on 2024-05-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0009_alter_issuecategory_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='max_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='issue',
            name='min_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
