# Generated by Django 4.0.7 on 2024-05-28 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0010_issue_max_price_issue_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issue.issue'),
        ),
    ]
