# Generated by Django 4.0.7 on 2024-05-31 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0011_tag_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='issue',
        ),
    ]
