# Generated by Django 4.0.7 on 2024-06-04 15:48

import cheatgame.issue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0013_issuereport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'DURING'), (2, 'DONE'), (3, 'CANCELED'), (4, 'IMPERFECT')], default=cheatgame.issue.models.IssueReportStatus['IMPERFECT']),
        ),
    ]
