# Generated by Django 4.0.7 on 2023-12-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_attachment_title_alter_label_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('product', 'category')},
        ),
    ]
