# Generated by Django 4.0.7 on 2024-01-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_quantity_delete_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='device_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
