# Generated by Django 4.0.7 on 2024-01-24 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_device_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='product.product')),
            ],
        ),
    ]
