# Generated by Django 4.0.7 on 2024-01-25 21:31

import cheatgame.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.IntegerField(choices=[(1, 'PRODUCT'), (2, 'FEATURE'), (3, 'BRAND'), (4, 'BLOG'), (5, 'SERVICE'), (7, 'GAME'), (8, 'GIFTCART')], db_index=True, default=cheatgame.product.models.CategoryType['PRODUCT']),
        ),
    ]
