# Generated by Django 4.0.7 on 2024-02-24 19:30

import cheatgame.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_delete_deliverytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.IntegerField(choices=[(1, 'GUARANTEE'), (2, 'INSURANCE'), (3, 'CAPACITY')]),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_type',
            field=models.IntegerField(choices=[(1, 'BRAND'), (2, 'GENERAL'), (3, 'CONSOLE'), (4, 'CAPACITY')], default=cheatgame.product.models.LabelType['GENERAL']),
        ),
    ]
