# Generated by Django 4.0.7 on 2024-05-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_off_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
