# Generated by Django 4.0.7 on 2023-12-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_baseuser_verify_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='verify_type',
            field=models.IntegerField(blank=True, choices=[(1, 'PHONENUMBER'), (2, 'EMAIL')], null=True),
        ),
    ]
