# Generated by Django 4.0.7 on 2023-12-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_baseuser_verify_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
