# Generated by Django 4.0.7 on 2024-01-24 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productnote'),
        ('users', '0008_favoriteproduct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteproduct',
            unique_together={('user', 'product')},
        ),
    ]
