# Generated by Django 4.0.7 on 2024-02-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_favoriteproduct_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=15),
        ),
    ]
