# Generated by Django 4.0.7 on 2024-02-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryschedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='deliveryschedule',
            name='end',
        ),
        migrations.RemoveField(
            model_name='deliveryschedule',
            name='start',
        ),
    ]
