# Generated by Django 4.0.7 on 2024-02-19 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_deliveryschedule_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryschedule',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryschedule',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
