# Generated by Django 4.0.7 on 2024-02-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_address_postal_code'),
        ('shop', '0003_deliveryschedule_end_deliveryschedule_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydata',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.address'),
        ),
    ]
