# Generated by Django 4.0.7 on 2024-02-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_deliverydata_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytype',
            name='side',
            field=models.IntegerField(choices=[(1, 'RECIEVEFROMUSER'), (2, 'SENDTOUSER')]),
        ),
    ]
