# Generated by Django 4.0.7 on 2024-03-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_deliverydata_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_game',
            field=models.BooleanField(default=False),
        ),
    ]
